(define (f n)
  (cond ((< n 3) n)
    (else (+ (f (- n 1)) (* 2 (f (- n 2))) (* 3 (f (- n 3)))))))
(f 4)
(f 11)
(define (g n)
  (_g n 2 1 0))
(define (_g n a b c)
  (cond ((<= n 2) a)
        (else (_g (- n 1) (+ a (* 2 b) (* 3 c)) a b))))
(g 4)
(g 11)
