(define (even? n)
  (= (remainder n 2) 0))
(define (double x)
  (* x 2))
(define (halve x)
  (/ x 2))
(define (mul a b)
  (cond ((= a 0) 0)
        ((= a 1) b)
        ((even? a) (mul (halve a) (double b)))
        (else (+ b (mul (halve a) (double b))))))
(mul 4 8)
