(define (runtime) 
  (current-milliseconds))
(define (pow2 n)
  (* n n))
(define (smallest-divisor n)
  (find-divisor n 2))
(define (find-divisor n test-factor)
  (cond ((> (pow2 test-factor) n) n)
        ((= (remainder n test-factor) 0) test-factor)
        (else (find-divisor n (+ test-factor 1)))))
(define (prime? n)
 (= (smallest-divisor n) n))
(define (time-prime-test n)
  (newline)
  (display n)
  (start-prime-test n (runtime)))
(define (start-prime-test n start-time)
  (if (prime? n)
    (report-prime (- (runtime) start-time)) -1))
(define (report-prime elapsed-time)
  (display " *** ")
  (display elapsed-time))
(define (search-for-primes a b)
  (cond ((even? a) (_search-for-primes (+ a 1) b))
        (else (_search-for-primes a b))))
(define (_search-for-primes a b)
  (time-prime-test a)
  (if (< a b) (_search-for-primes (+ a 2) b) 0))
(search-for-primes 3 11)
(search-for-primes 1001 1055)
(search-for-primes 10001 10055)
(search-for-primes 100001 100055)
