(define tolerance 0.00001)
(define (fix-point f first-guess)
  (define (close-enough v1 v2)
    (< (abs (- v1 v2)) tolerance))
  (define (try-it x)
    (let ((next (f x)))
    (cond ((close-enough x next) x)
          (else (try-it next)))))
  (try-it first-guess))
(fix-point cos 1.0)
(fix-point (lambda (x) (+ 1 (/ 1 x))) 1.0)
